### ISSUE TITLE
fire_flint_steel.png texture missing

### ISSUE THREAD

**Issue by fireglow** [Ezhh/abriflame#1]
abriflame/init.lua
100:    inventory_image = "fire_flint_steel.png",

however, there is no such texture.
in-game error messages also appear upon opening unified_inventory:
https://files.catbox.moe/7sq3k4.png

**Comment by Ezhh** [comment]
The texture is present in MTG, but I made the mistake of assuming it was in default, when it's actually in fire.
https://github.com/minetest/minetest_game/blob/master/mods/fire/textures/fire_flint_steel.png

I've updated depends.txt. Please let me know if that solves it for you, and thanks for letting me know.

**Comment by fireglow** [comment]
The issue persists.
But probably because we're using a fire mod that doesn't have the texture in it.
I've "solved" it by just placing the original texture in abriflame/textures/.

Last edit: If the fire mod has the fire_flint_steel.png texture, it also works. So your fix did the trick. Thanks :)

**Comment by Ezhh** [comment]
Awesome - thanks for taking the time to report and test. 
It's probably never come up before because most people just use MTG as is, so if they have default they have the texture too, but the depends file definitely needed fixing.

Any other issues, please just let me know.
